# Generated by Django 5.2.13 on 2026-05-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='fio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='telegram',
            field=models.CharField(blank=True, help_text='Telegram username yoki raqam', max_length=255),
        ),
    ]
